### ISSUE TITLE
Add more lines to the cloudy based grids

### ISSUE THREAD

**Issue by stephenmwilkins** [flaresimulations/synthesizer#102]
At the moment the cloudy grids assume a select set of lines. However, this may be too limited. My recollection was that this was based on some threshold.

There are probably too many lines to include them all. Not sure of a good way to filter. Probably best to do is to use some threshold based on the reference age/metallicity grid point but this could result in different lines from different models.

@christopherlovell thoughts?

**Comment by aswinpvijayan** [comment]
I think there is an option in cloudy to print only lines with some relative strength to the Halpha or Hbeta line. However, this too would give varying number of lines.

**Comment by stephenmwilkins** [comment]
Yes. I also worry that defining the available lines based on the reference grid point will miss lines that only pop up at low/high-metallicity. I suppose the answer might be to be very liberal, but this will grow the grid.
