### ISSUE TITLE
Add AGN templates, and an AGN source class

### ISSUE THREAD

**Issue by christopherlovell** [flaresimulations/synthesizer#106]
Ideally to allow the possibility of post processing with CLOUDY for ionisation studies, e.g. https://arxiv.org/abs/2301.07745

**Comment by stephenmwilkins** [comment]
Jussi did a lot of CLOUDY modelling of AGN which we should bring in here. Not sure who we can get to do it though.

**Comment by aswinpvijayan** [comment]
Cigale has implemented the SKIRTOR AGN models, which could be a template library.

**Comment by WillJRoper** [comment]
This was solved by #425, although maybe in a slightly different guise than was planned here.
