### ISSUE TITLE
Allow images to use electron / s units

### ISSUE THREAD

**Issue by WillJRoper** [flaresimulations/synthesizer#109]
To match low-level observation data, we need to include routines to convert images (and noise contributions) to electrons per second.

**Comment by stephenmwilkins** [comment]
I've thought about this and it's trivial just using a zero point **but** the JWST pipeline by default produces images in nJy/Sr so I suggest we just use that as our default imaging unit. Now, there might be a need to convert to e/s and vice versa to properly account for poisson noise though.

Which reminds me what are the default units?

- for synthetic observations I suggest nJy/Sr
- for "physical" images L_nu/pc^2?
