### ISSUE TITLE
Examples need to be updated

### ISSUE THREAD

**Issue by WillJRoper** [flaresimulations/synthesizer#113]
I've run all the examples currently on main and a number of them need updating to reflect recent changes. In addition, the vast majority need more documentation (a doc string at the top, an explanation of what each bit is doing etc.)

The reasons for errors are all fairly simple and I've already fixed a bunch but here is the list of outstanding issues:

## Checklist
- [ ] examples/cloudy/run_cloudy.py
- [ ] examples/cloudy/analyse_cloudy.py
- [ ] examples/grids/yggdrasil_example.py
- [ ] examples/grids/plot_spectra_age.py
- [ ] examples/grids/plot_spectra_cloudy.py
- [ ] examples/cosmo/camels.py
- [ ] examples/cosmo/flares.py
- [ ] examples/particle/create_sampled_sed.py
- [ ] examples/particle/create_flux_image_multifilter.py
- [x] examples/parametric/make_image.py
- [x] examples/parametric/generate_observed_sed.py
- [x] examples/parametric/generate_lines.py

**Comment by christopherlovell** [comment]
parametric examples now working, except for `generate_composite_galaxy.py` which fails on the addition:

        new_galaxy.images[img_name] = image + second_galaxy.images[img_name]
        TypeError: unsupported operand type(s) for +: 'ParametricImage' and 'ParametricImage'
