### ISSUE TITLE
fesc could be an array.

### ISSUE THREAD

**Issue by WillJRoper** [flaresimulations/synthesizer#124]
Should we assume this as standard and simply make an fesc array if a single value is passed? My vote is yes. Its a small temporary memory footprint increase.

**Comment by stephenmwilkins** [comment]
Yes, if the overhead is small. But is it?

**Comment by WillJRoper** [comment]
Relative to everything else yes it's small. At worst it'll be a 64-bit number for every star and it will be very short-lived since it only really matters for the spectra creation. Really it should probably be 32-bit if not 16-bit since it's unlikely to be high precision.
