### ISSUE TITLE
Automatically redshift filter transmission

### ISSUE THREAD

**Issue by stephenmwilkins** [flaresimulations/synthesizer#131]
At the moment I believe we still have to give a new redshift grid when the filter transmission is defined. The original reason for this is that it avoided redshifting/interpolating the filter more than once. However, it would be good if the broadband luminosity generation knew to redshift/interpolate if a new wavelength grid wasn't applied.

**Comment by WillJRoper** [comment]
I'm not sure I understand. I've just modified the filter application method to take an x array for the transmission integration. This means you can pass whatever x array you fancy but that must always be the same as the SED and Filter. We can't chop and change and I don't see the use cases where you do chop and change? Surely you use the grid lam and that's that.

**Comment by stephenmwilkins** [comment]
Let's say I have an Sed and I want to apply some filters to it. At the moment I have to do:

```
sed = Sed(...)
fc = FilterCollection([...], new_lam = sed.lam)
sed.get_broadband_luminosities(fc)
```

but I really want to do this:

```
fc = FilterCollection([...])
sed = Sed(...)
sed.get_broadband_luminosities(fc)
```

In this case `get_broadband_luminosities` needs to tell fc to rebin the filters if the wavelength grids don't agree.
