### ISSUE TITLE
Line of sight approach

### ISSUE THREAD

**Issue by WillJRoper** [flaresimulations/synthesizer#14]
- Functions in script los.py so tools can be used standalone. 
- Galaxy class has a method to call los calculation. (Should the SED class also have this option?)
- Galaxy class needs to load gas data.
- Need kernels in kernel.py function (or allow the user to supply kernel function). 
- Need geometry/orientation helper functions. 

Is the weighted grid compatible with LOS calculation? (i.e. former is a grid, latter is not): @christopherlovell.

**Comment by christopherlovell** [comment]
Not sure what you mean. The grid is just a way of getting the emission for a given particle. Can be vectorised to get emission from multiple particles but not necessary. 

Not sure what the alternative to the grid is

**Comment by christopherlovell** [comment]
addressed predominantly in #85
