### ISSUE TITLE
Look at providing scalings for individual abundances

### ISSUE THREAD

**Issue by stephenmwilkins** [flaresimulations/synthesizer#144]
N/O appears to be a function of Z (i.e. N does not uniformly scale with Z). We might want an elegant way to define additional scalings.

**Comment by WillJRoper** [comment]
@stephenmwilkins while you're working on the abundance stuff could you maybe look at this? Is this still something you're interested in?

**Comment by WillJRoper** [comment]
@stephenmwilkins is the fixed by #503?

**Comment by stephenmwilkins** [comment]
Yes. Forgot about this issue.
