### ISSUE TITLE
generate_spectra and generate_lnu are the exact same method 

### ISSUE THREAD

**Issue by WillJRoper** [flaresimulations/synthesizer#171]
https://github.com/flaresimulations/synthesizer/blob/8a76e57f50c68dd9d5e4802aa877c72b380c4a67/synthesizer/galaxy/particle.py#L262

These methods are identical except generate_lnu returns the array. This is easily achieved with a single method and an optional return. 

I'm going to start a branch where I maintain the front end but streamline the back end. 

Additionally all the new front facing functions need particle level equivalents.

**Comment by christopherlovell** [comment]
`generate_spectra` is the deprecated method left over for compatibility reasons. It should be binned, but we first need to ensure it doesn't break imaging routines reliant on it. See #167

`generate_lnu` is the new method that should be used going forward. It is the base method from which other methods are wrappers (e.g. `generate_stellar_spectra`, `generate_nebular_spectra`)

**Comment by christopherlovell** [comment]
see also comment in the method description https://github.com/flaresimulations/synthesizer/blob/8a76e57f50c68dd9d5e4802aa877c72b380c4a67/synthesizer/galaxy/particle.py#L188

`TODO: DEPRECATED, left to avoid compatibility issues (for now)`

**Comment by christopherlovell** [comment]
If you want to bin it and run all the example scripts that would be hugely appreciated

**Comment by WillJRoper** [comment]
The `generate_lnu` function demands you use one of the many wrappers then.

**Comment by WillJRoper** [comment]
I'll remove the deprecated method and adhere to the structure for now but this needs a rethink in the future. Once you include the particle versions we will have 14 different methods for spectra on a galaxy, not including line related ones. That is too many.

**Comment by WillJRoper** [comment]
Addressed in #209
