### ISSUE TITLE
The spectra functions on galaxies have far too many return options

### ISSUE THREAD

**Issue by WillJRoper** [flaresimulations/synthesizer#172]
Each of the spectra methods have numerous return options which I'm sure will be rarely used. 

```        
         if update:
            self.spectra['attenuated'] = sed

        if sed_object:
            return sed
        else:
            if return_wavelength:
                return grid.lam, lnu
            else:
                return lnu
```

I can see why you might want to return an array instead an SED object but I can't see any harm in always "updating". The wavelength is attached to the sed so is entirely redundant. I'd argue for simplicity and jsut always attach and return an sed object but I know I'll get push back. So why don't we just always attach and return the sed object and the array. 

Think of numpy.histogram where it returns the bins but those are redundant if you passed a bins array. Instead of including extra arguments they just always return it. The memory usage of an SED object is minimal overhead on top of the lnu and wavelength arrays which already exist in memory regardless.

**Comment by WillJRoper** [comment]
But we've shown it has 0 effect on performance?

**Comment by WillJRoper** [comment]
Remember we need to document all these arguments so we are adding a bunch of extra lines that add 0 useful functionality.

**Comment by christopherlovell** [comment]
on performance, speed: no, but memory will definitely be affected?

**Comment by WillJRoper** [comment]
Just did the calculation. The SED object overhead is 0.5% relative to sum of the lnu and lam arrays. It really is nothing. Additionally, I just realised that we have placed flux calculations on the SED so if you don't return an SED object you can't get flux. 

Sure, its nice to not worry about ignoring the returned object you do not need in the one case where you only want an array and not the object but in every other case it makes sense to return it so why introduce the messy logic and extra arguments? All you need is:
```
sed, lnu = gal.get_*_spectra(*)
```
which becomes 
```
_, lnu = gal.get_*_spectra(*)
```
If you only want the array.

**Comment by christopherlovell** [comment]
Okay. I had inferred from discussions online (e.g. [here](https://pythonspeed.com/articles/python-object-memory/)) that this was a bigger issue. As long as it is not the case when moving to hundreds of thousands of objects then feel free to remove.

**Comment by WillJRoper** [comment]
What is quoted in that article is true. We should use things like `__slots__` (in fact that implemented in places for exactly this reason). 

Regardless, I'll switch it up and on the same branch implement the particle versions of the SED methods.
