### ISSUE TITLE
Dealing with super-resolution parametric images

### ISSUE THREAD

**Issue by stephenmwilkins** [flaresimulations/synthesizer#181]
Currently parametric images doesn't create super-resolution images.

**Comment by WillJRoper** [comment]
This is all handled by the base Image class so should be accessible by inheritance. Internally the scaling is only automatically called if a PSF image is being made. However, I'm not sure if we even want to be doing this automatically. Maybe we should leave all of that in the hands of the user and only provide the methods? In fact... I think I prefer that.

**Comment by stephenmwilkins** [comment]
Hmm... I'm a little confused about how this works and what is the best approach.

At initialisation the user specifies a desired resolution. At this point the code goes ahead and makes an image at that resolution?

If, later, the user decides they want to include the PSF, what happens? I think the simplest thing would be if the supplied PSF somehow comes with a resolution. At this point the image is regenerated at the resolution of the PSF before being downsampled to the original desired resolution.

**Comment by stephenmwilkins** [comment]
In the context of `ParametricImage` I guess it needs a method that creates an image for an arbitrary resolution that exactly mirrors the method in `ParticleImage`.

**Comment by WillJRoper** [comment]
What currently happens is the `resolution` is provided and considered the native pixel scale. If a `super_resolution_factor` is passed then the pixel scale is resampled to that scale. The "standard" image (no noise, no PSF) is then made at the resampled resolution. If a PSF image is made both the standard and image with PSF are **downsampled back to the native resolution** after convolution. However, the methods to resample are there so the user can do as they please with resampling arbitrarily outside this process.

**Comment by WillJRoper** [comment]
There isn't a "what if later" the image object should be initialised with all the planned inputs. I can't see a workflow where you would change this after the fact. An image/ifu doesn't need recomputing.

**Comment by WillJRoper** [comment]
I'm closing this. This is indeed handled by the `resample_image` static method on `Image` and the PSF gubbins doesn't care if it's a particle or parametric image so that handles the super-resolution factor properly. I'm not sure what the original issue was because this functionality has existed for a very long time.
