### ISSUE TITLE
PSF class

### ISSUE THREAD

**Issue by stephenmwilkins** [flaresimulations/synthesizer#185]
Would be nice to have a PSF class that provides some in-built standard PSFs.

**Comment by WillJRoper** [comment]
I dont think this is worthwhile. The PSF can be created by a single scipy (or similar) function (see the example). My stance has always been we let the user pass whatever they want. I’m not dead set against it but I just don’t see the point.

**Comment by stephenmwilkins** [comment]
OK then, well we at least need examples e.g. use of a 2D Gaussian and maybe WebbPSF
