### ISSUE TITLE
Return intrinsic / stellar SED from dust get_spectra methods

### ISSUE THREAD

**Issue by christopherlovell** [flaresimulations/synthesizer#236]
# The problem
The heavy lifting when generating spectra from particles is done in `generate_lnu`. Currently, if you wish to generate spectra using a dust model, but also want the intrinsic or stellar spectra, you have to run the dust method and then the intrinsic method _individually_, each calling `generate_lnu`.

# The solution
Ideally each dust method should update the intrinsic or stellar sed in the `.spectra` attribute of each galaxy object by default.

# Other thoughts
This is somewhat related to the problem of applying multiple grids to the same galaxies, e.g. to test different SPS models, or the inclusion of nebular processing. In this case, one has to load a new grid and run `generate_lnu` for each object. Each call to `generate_lnu` assigns each particle to an N-d grid, which then gets multiplied by the grid file. This sparse grid that gets calculated can be identical for some grid file applications. There should be a simple way of getting hold of that grid and applying different grid models over the top. This is more of a stretch goal.

**Comment by WillJRoper** [comment]
Absolutely agreed with the solution.

Re the stretch goal: The parametric version does do this duplication with the sparse grid. The particle version never makes that grid, it's a simple loop finding the indices of a particular particle and adding those to the spectra with the appropriate weight. It may be (probably is) possible to return the indices found in this *if* the grids have the same properties along the axes but that surely isn't guaranteed? 

We may have to accept that the multiple runs of `generate_lnu` are a necessity for the multiple grid comparison use case. I'm not sure we can always count on the axes being the same.

**Comment by WillJRoper** [comment]
No longer applicable. Spectra are stored on the component (or within the galaxy). The workflow now is such that you don't do duplicate grid weight calculations.
