### ISSUE TITLE
MIssing files in cloudy grid creation directory 

### ISSUE THREAD

**Issue by christopherlovell** [flaresimulations/synthesizer#241]
**Describe the bug**
`default_lines.dat` and `interesting_lines.dat` don't exist in the `generate_grids/cloudy/` directory

**To Reproduce**
Run `create_synthesizer_grid.py`, errors here:

https://github.com/flaresimulations/synthesizer/blob/a1bd12ad5a138ec56b8e97fbe0789feeab704fd8/generate_grids/cloudy/create_synthesizer_grid.py#L219

**Comment by stephenmwilkins** [comment]
This has now been superseded in `grid_update` branch
