### ISSUE TITLE
generate sfzh methods should return more informative errors 

### ISSUE THREAD

**Issue by christopherlovell** [flaresimulations/synthesizer#245]
Following methods are all similar, but where incorrect arguments are provided (e.g. a single age to `generate_sfzh_from_array`) they fail without explaining that there are other methods. 

`generate_sfh`
`generate_instant_sfzh`
`generate_sfzh`
`generate_sfzh_from_array`

Arguably these methods could all be combined and handle the various arguments under the hood.

https://github.com/flaresimulations/synthesizer/blob/048662537079c165c8758578b4e3a272f47301b4/synthesizer/parametric/sfzh.py#L144

**Comment by WillJRoper** [comment]
Missed this issue. I totally agree! Although, I feel as if these functions should all really be implemented in the `__init__` of `BinnedSFZH` and a star formation/metallicity equivalent rather than stand alone functions.
