### ISSUE TITLE
Metallicities are offset when plotting a binned sfhz

### ISSUE THREAD

**Issue by jackcturner** [flaresimulations/synthesizer#251]
When plotting a binned sfhz, the position of the heatmap on the metallicity axis is offset from the value shown by the grey histogram. The histogram bar is at the correct value, whereas the heatmap is at lower metallicity. 

Printing the sfhz shows the correct metallicity value, so this is probably just a visual issue. 

<img width="742" alt="Screenshot 2023-08-08 at 11 06 26" src="https://github.com/flaresimulations/synthesizer/assets/52683568/dceb3858-2d21-41fe-90a9-4d1094f4f009">

**Comment by WillJRoper** [comment]
I notice this in the past actually. Think I’ve fixed it in a branch where I was revamping the SFZH functionality. I’ll have a look and separate out a fix from my larger developments.
