### ISSUE TITLE
Check that sfzh hasn't been passed to a particle galaxy object, raise a warning if so 

### ISSUE THREAD

**Issue by christopherlovell** [flaresimulations/synthesizer#252]
https://github.com/flaresimulations/synthesizer/blob/39f46a4e569405a26c5a646c386006bdb5755b29/synthesizer/particle/galaxy.py#L31

**Comment by WillJRoper** [comment]
As stated separately, `name` should be one of the last arguments to a Galaxy and as above. Can't be too granular with checks or we will be checking every possible iteration of what a user could possibly accidentally do.

**Comment by WillJRoper** [comment]
We could actually solve this and a lot of other particle vs parametric woes if we flipped to a factory pattern. 

In a factory pattern, we'd have a generic `Galaxy` which the user imports. All that Galaxy does is initialise and return the correct type of `xxxx.Galaxy` based on what it was passed as arguments.  This protects against misuse of `Galaxy`s and simplifies the frontend the user needs to understand by removing the question of "Which galaxy do I need?".

This could probably also be helpful in the complex mire in the imaging when it comes to angular vs cartesian + particle vs parametric + images vs maps.

**Comment by christopherlovell** [comment]
I like the factory pattern concept
