### ISSUE TITLE
Allow galaxies to have AGN

### ISSUE THREAD

**Issue by stephenmwilkins** [flaresimulations/synthesizer#254]
It would be great if `Galaxy` objects could have a (or multiple) AGN attached to them. When creating images those AGN shouldn't be smoothed other than by the PSF.

**Comment by WillJRoper** [comment]
Easily done, just need an AGN object which inherits from the base `Particle`. 

I think its conceptually easier if an AGN object contains multiple AGN rather than a galaxy containing multiple AGN objects.

**Comment by christopherlovell** [comment]
Agreed. This makes it identical to the `stars` and `gas` particle classes, in that each object contains arrays of stars and gas particles, rather than individual objects for each one.

**Comment by stephenmwilkins** [comment]
Agreed, that makes most sense. Does anyone have any strong objection between AGN and SMBHs? I guess they are only going to make a difference to the SED if they are active.

**Comment by christopherlovell** [comment]
Good question. I would suggest `blackholes` as a catch all term. You may wish to include all black holes when reading in cosmo sim data, for example, but not all will be active

**Comment by WillJRoper** [comment]
I like `BlackHoles`, which explicitly states it can be plural and avoids any arguments about mass ranges and activity.

**Comment by stephenmwilkins** [comment]
OK.
