### ISSUE TITLE
Rename spectra to be more explicit about the origin.

### ISSUE THREAD

**Issue by stephenmwilkins** [flaresimulations/synthesizer#255]
Rename spectra to be more explicit about the origin. For example, use this naming scheme:

```
- *_incident
- *_transmitted
- *_nebular
- *_nebular_continuum
- *_intrinsic
- *_attenuated
- *_dust 
```
where * is [stars, agn, total].

**Comment by christopherlovell** [comment]
we should also discuss the use of aliases for grids that have not been cloudy post-processed. We've had this discussion a number of times but I can't remember the conclusion(s) (apologies). 

In summary, should these non-cloudy processed grids take the `*_intrinsic` spectra and create aliases for `*_incident` and `*_transmitted`. My feeling is that they should *not*, and that methods that rely on these keys should return a meaningful error telling the user they are not using a compatible grid file.
