### ISSUE TITLE
Add Yggdrasil popIII SPS models

### ISSUE THREAD

**Issue by christopherlovell** [flaresimulations/synthesizer#26]
available [here](https://www.astro.uu.se/~ez/yggdrasil/yggdrasil.html)

**Comment by aswinpvijayan** [comment]
Lets just pick the instantaneous model and vary all the other parameters i.e., IMF and gas covering factor

**Comment by christopherlovell** [comment]
within the synthesizer grids framework that means individual grids for each one right?

**Comment by aswinpvijayan** [comment]
Yes, with a distribution of ages for these grids

**Comment by christopherlovell** [comment]
added in #37
