### ISSUE TITLE
Inconsistencies in the naming of spectra

### ISSUE THREAD

**Issue by stephenmwilkins** [flaresimulations/synthesizer#266]
As revealed by looking at intrinsic spectra generation there is inconsistency in how the output spectra are named for the different methods. 

Resolution is that I will go through all the methods and make sure they're consistent and write documentation.

**Comment by christopherlovell** [comment]
Fix in progress in #262

**Comment by WillJRoper** [comment]
Was this solved in #262 or is there more to do?
