### ISSUE TITLE
test grid smears out lines

### ISSUE THREAD

**Issue by stephenmwilkins** [flaresimulations/synthesizer#272]
Test grid creation smears out emission lines to several bins which is undesirable. This may need some thinking about how best to do the downsampling.

**Comment by christopherlovell** [comment]
can we finely sample a couple of specific emission lines, and use these in examples?

**Comment by WillJRoper** [comment]
This would be solved by throwing away the test grid from the repo and instead hosting a single grid somewhere accessible by a `wget` or similar script. We could download the file to a specified location as a GitHub action prior to the tests and use a proper full-fat grid for those tests. 

If a user needs to run with the test grid they can then also run the get script. This is how SWIFT handles the examples included in the examples directory.

**Comment by WillJRoper** [comment]
Indeed.

That's the trouble. I'm not sure if we can from Apollo, @stephenmwilkins?

**Comment by christopherlovell** [comment]
I can maybe sort something from Sciama. Let me know
