### ISSUE TITLE
PowerLaw.attenuate doesn't do what it describes

### ISSUE THREAD

**Issue by WillJRoper** [flaresimulations/synthesizer#316]
The docstring for PowerLaw.attenuate says "Provide the transmitted flux/luminosity fraction" but none of the arguments are the flux and it simply returns e^-tau. This is either an unfinished method or a misleading description.

**Comment by WillJRoper** [comment]
I'm guessing this replaces the previous `T` method and should actually be called "transmission"? @stephenwilkins

**Comment by stephenmwilkins** [comment]
I think it was @aswinpvijayan who originally named and wrote these (maybe?) but I agree we could name these better.

How about `get_tau` and `get_transmission` instead?

**Comment by WillJRoper** [comment]
Yea, I like it

**Comment by stephenmwilkins** [comment]
I assume these should also return a 2D array (index, lam) when an array of `tau` values are provided?

**Comment by WillJRoper** [comment]
If you can do it please do, one less thing for that PR down the road! And yes they should return a 2D array in that event
