### ISSUE TITLE
Real grids now won't work

### ISSUE THREAD

**Issue by stephenmwilkins** [flaresimulations/synthesizer#323]
Since grid names can include "." before the extension this breaks for real grids I'm afraid.

```
# Have we been passed an extension?
        if len(grid_name.split(".")) > 1:
            self.grid_ext = grid_name.split(".")[-1]
        else:
            self.grid_ext = "hdf5"
```

**Comment by stephenmwilkins** [comment]
I should have caught this earlier.

**Comment by WillJRoper** [comment]
In the nicest way: why in gods name are dots allowed in filepaths!?

**Comment by WillJRoper** [comment]
They have a specific meaning in filepaths. If they proceed a directory it means hidden, in a filename they denote where the extension is. We should absolutely not have any `.`s in the filenames themselves. 

This is not an issue with the above code but rather than naming of grids.
