### ISSUE TITLE
High resolution wavelength grids are awfully memory hungry

### ISSUE THREAD

**Issue by WillJRoper** [flaresimulations/synthesizer#335]
When making an image of a galaxy with 33 million particles I encountered seg faults all over the place. At first, I thought this was the code but it wasn't a single point failing. 

Turns out I ran out of memory either during spectra creation or IFU making (changed depending on the number of elements). This isn't an issue for integrated spectra, however, the moment you have a high-resolution wavelength grid (~88,000 elements for the BPASS grid I used) and lots of particles this will fall apart. 

Proposed solutions:
- Allow the user to apply wavelength cuts to the grid (and thus anything derived from it) to remove elements not used in their current analysis. We carry around a lot of array elements which are effectively 0 compared to the elements with meaningful flux.
- Optional downsampling of spectra for image creation (will smear out lines, so only works when working with photometry and even then not ideal because lines may shift flux outside of the filter curve). 
- Completely rethink the entirety of particle spectra + image creation to improve the memory usage (I obviously don't want to do this. Everything will have to be done on the fly and subsequently deleted when stored in an image. The IFUs also necessitate the current structure).

**Comment by christopherlovell** [comment]
It would be useful to understand _where_ it's falling over. If you're simply having to create 33 million * N_wavelength arrays and store them simultaneously in memory then there is no way of getting around this - that's 11.6 Tb of memory if each value is float32, N_wavelength=88000.

If we want to be able to support such high resolution input data I suggest we need to provide methods that can loop over particles in a smarter way. But this is obviously quite a lot of work, and will require dumping data on the fly as you mention. I don't really see a way around this though. 

The first two methods you propose are fine, we can write dedicated methods for this, but as you point out they are not ideal.

This does raise the point that storing particle spectra by default is _very_memory hungry. I'd argue we should leave that up to the user.

**Comment by WillJRoper** [comment]
The thing is it just falls over at random points. I was on the login node of cosma so the amount of available memory fluctuated. 

Its a lot of work to do something like that and completely flies in the face of the entire structure of Synthesizer. Note that IFUs will always be prohibitively expensive for large pixel numbers! 

However, look at this spectra from what I was playing with (over MPI and collect on a single rank to plot):

![colibre_spectra_attenuated](https://github.com/flaresimulations/synthesizer/assets/40025495/5661ee14-8b09-4143-9c50-185042fd3d2b)

The vast majority of the spectrum (there's loads to the left I've cut off with the axis limits too) is not within the wavelength range of the filters and everything to the left is 10**20 times smaller than even the lowest value shown in the plot. We don't need to be carrying around all these elements unless we really care about them.

**Comment by WillJRoper** [comment]
After conversations outside this thread, I think @christopherlovell is right. The best way to address this while ensuring consistency end to end in the wavelength grid is to allow the user to pass a wavelength array of their own design (limits and resolution) to the `Grid` at initialisation. This will enforce a consistent wavelength grid at all downstream points while limiting the spectra only to a range the user has defined at a resolution the user needs. 

I vaguely remember this being possible in the past (@stephenmwilkins?) but appears not to be an option now. I think this will be best achieved via `scipy.interpolate.griddata`.
