### ISSUE TITLE
Bug in Parametric line attenuation L388

### ISSUE THREAD

**Issue by aswinpvijayan** [flaresimulations/synthesizer#357]
(https://github.com/flaresimulations/synthesizer/blob/6b59de6c00977d3913bd29b9a3a6f15216d2569f/synthesizer/parametric/galaxy.py#L388)
The line needs ot be changed to `for line_id, intrinsic_line in intrinsic_lines.lines.items():`

**Comment by christopherlovell** [comment]
do you want to raise a small PR? Or I can do tomorrow
