### ISSUE TITLE
Bug in composite images example leading to failing docs

### ISSUE THREAD

**Issue by christopherlovell** [flaresimulations/synthesizer#359]
`examples/parametric/plot_composite_ga;axy.py` currently fails on line 106 with a segfault:

    
    # make images
    bulge_img = bulge.make_images(
        resolution=resolution,
        filters=filters,
        sed=bulge.spectra["incident"],
        fov=fov,
    )

To reproduce, run this example. Should run without issues. The disk imaging example just above this line runs without issue, so unclear what is unique about this particular instance.

**Comment by WillJRoper** [comment]
I can't reproduce this issue locally. Could it be a memory-related segfault? The images aren't particularly large but if the wavelength range is large I could foresee it running out of memory. Like what I was facing before.
