### ISSUE TITLE
A `PhotometryCollection` would enable units and nice functionality

### ISSUE THREAD

**Issue by WillJRoper** [flaresimulations/synthesizer#384]
As much as I want to avoid introducing more and more classes... I've been convinced a photometry container class would be nice both for associating units with results and for adding helper functionality.

There may be some gotchas with how exactly to handle the creation of `PhotometryCollection`s but it will probably just require instantiating one and adding photometry after instantiation rather than at instantiation. This is because Photometry is calculated on a per `Filter` basis and not at a `FilterCollection` level, and I don't think that should change!

**Comment by WillJRoper** [comment]
This would enable automatic unit conversions cleanly via helpful attributes computed in the setter, e.g.
```
photometry = PhotometryCollection(...)
phot = filt.apply_filter(spectra, ...)

# For rest frame only
photometry.add(lnu=phot)

# For flux
photometry.add(fnu=phot)

photometry[filter_code].mag
photometry[filter_code].lnu
# or
photometry[filter_code].fnu
```

**Comment by christopherlovell** [comment]
Agree, but can we just call it a `Photometry` class, rather than `PhotometryCollection`? It can be used in the plural as well as the singular anyway. "The photometry are contained..." etc.
