### ISSUE TITLE
Typo in read_lines Exception string in grid.py

### ISSUE THREAD

**Issue by ConnorSF** [flaresimulations/synthesizer#395]
The read_lines Exception `if read_line is not False `is worded incorrectly in grid.py:

current wording: "No lines available on this grid object. Either set **`read_lines=True`**, or load a grid containing line information"

correct wording:  "No lines available on this grid object. Either set **`read_lines=False`**, or load a grid containing line information"

**Comment by christopherlovell** [comment]
Thanks Connor. Could you raise a small PR to fix this?

**Comment by ConnorSF** [comment]
Of course. Consider it done
