### ISSUE TITLE
Add lum and llam to Sed

### ISSUE THREAD

**Issue by stephenmwilkins** [flaresimulations/synthesizer#403]
Add `lum` (`nu*lnu`) and `llam` to `Sed`.

**Comment by WillJRoper** [comment]
Can we rename these variables to be a bit more informative at the same time? `llam` is particularly meaningless 😅

**Comment by christopherlovell** [comment]
Are these needed internally or externally? Can we not save these and make them class properties that are calculated when called? 

when doing this on cosmological simulations with a lot of galaxies the memory requirements of carrying round all these definitions is already quite high.

If used externally, We should, however, make it clear to developers which ones need to be used when doing internal calculations to avoid unnecessary compute
