### ISSUE TITLE
Use a single argument on parametric `Stars` to accept sfh/Z function or array

### ISSUE THREAD

**Issue by christopherlovell** [flaresimulations/synthesizer#420]
There are currently two separate arguments on `Stars` to accept either functional forms of the SFH/Z distribution (`sf_hist_func` / `metal_dist_func`) and two arguments for arrays (`sf_hist` / `metal_dist`). Can we combine these, and have some logic in the background to interpret what the user provides?

The number of arguments could also be reduced / simplified by removing the `instant_sf` and `instant_metallicity` options, as these arguably can be accomodated within distributions, but no strong feelings on this point.

**Comment by WillJRoper** [comment]
Agreed! That would streamline things hugely. Just `sf_hist` and `metal_dist`? I don't see why we don't just fold the instantaneous ones in to. In hindsight, it is a bit cumbersome with individual arguments for both.
