### ISSUE TITLE
Add separate `f_esc` parameters for escape from HII regions and unattenuated light

### ISSUE THREAD

**Issue by christopherlovell** [flaresimulations/synthesizer#429]
Right now in the pacman model `f_esc` controls escape from photoionisation regions as well as light that remains unattenuated by ISM dust. We should have two parameters controlling both of these.

https://github.com/flaresimulations/synthesizer/blob/76cee693fbd73ec44403aceb5648da773b95e57f/src/synthesizer/components/stellar.py#L467

**Comment by aswinpvijayan** [comment]
Not sure about that. In case of star particles this is taken care of, as there can be sightlines with no dust. In case of parametric galaxies, the choice of your attenuation curve is supposed to handle the dust porosity.

**Comment by aswinpvijayan** [comment]
Changed my mind. I guess it might makes sense for paramtric galaxies

**Comment by christopherlovell** [comment]
I'm open to this just being documented better, but right now the docstring for this argument doesn't make this clear

**Comment by stephenmwilkins** [comment]
The pacman model is increasingly looking not like a pacman. I do see the point though, even if the labelling becomes even more complex.
