### ISSUE TITLE
do_grid_check in particle luminosity calculation, inequality operator

### ISSUE THREAD

**Issue by aswinpvijayan** [flaresimulations/synthesizer#432]
Bug:
Shouldn't all the logical operations here have an = as well, since the grids are evaluated exactly at the grid points in the SPS modela nd cloudy? @WillJRoper 
https://github.com/flaresimulations/synthesizer/blob/main/src/synthesizer/particle/stars.py#L386

**Comment by WillJRoper** [comment]
Possibly but even a particle equal to the grid edges is pinned to the edge. I think you could argue for both logical expressions.

**Comment by aswinpvijayan** [comment]
Yes, I saw thats what happens. Its just for having better clarity when it comes to the warning.

**Comment by WillJRoper** [comment]
So what do you argue for? An equals in the inequality? Or a change to the warning? I'm semi-keen to leave it as is.
