### ISSUE TITLE
`get_equivalent_width` does not belong on galaxy

### ISSUE THREAD

**Issue by christopherlovell** [flaresimulations/synthesizer#460]
Not sure why this method exists on a galaxy object. It just calls `measure_index` on each spectra object.

@ConnorSF could you provide some context?

**Comment by ConnorSF** [comment]
A call from galaxy to measure_index was done during the development of the measure_index feature on a previous version of synthesizer. If I recall correctly there was a parameter being passed that was not directly accesssible through the example script. 

This should probably work with a direct call now. I can sort that out if you'd like?

**Comment by christopherlovell** [comment]
That would be great. The `measure_index` method also needs looking at, since it's currently the slowest example in the documentation build. I've made a couple changes already (moving some of the compute outside the for loop... will push soon) but can probably benefit from vectorisation of many of the steps.

**Comment by ConnorSF** [comment]
Sure, no problem. I'll look into updating the measure_index method as well. Let me know once you've pushed and I'll get right on it.

**Comment by christopherlovell** [comment]
PR open here #461
