### ISSUE TITLE
Some SVO Filters have transmission >1

### ISSUE THREAD

**Issue by WillJRoper** [flaresimulations/synthesizer#523]
Certain filter curves from SVO have transmission values in the 10s (e.g. ~60 for GALEX being an example).

I wonder if some transmission arrays are quoted in percent. If so we should probably have something like

```
if self.t.max() > 1:
    self.t /= 100
```

For SVO filters specifically.

**Comment by christopherlovell** [comment]
As discussed on slack, this is the case for certain instruments that quote the transmission in terms of the effective area (cm^-2). e.g.

[GALEX](http://svo2.cab.inta-csic.es/theory/fps/index.php?mode=browse&gname=GALEX&asttype=)
[XMM](http://svo2.cab.inta-csic.es/theory/fps/index.php?mode=browse&gname=XMM&asttype=)

We should check the output of SVO where this is the case. I am not sure if a simple conversion exists.
