### ISSUE TITLE
'Emergent' spectra not generated when two component dust law is used and no dust emission law set in galaxy.stars.get_spectra_pacman()

### ISSUE THREAD

**Issue by tHarvey303** [flaresimulations/synthesizer#550]
You may already be aware of this issue, but attempting to run `galaxy.stars.get_spectra_pacman()` fails for certain combinations of inputs, detailed below. Apologies if anything isn't clear or you're already aware of this, I couldn't see a relevant open issue.  

**To Reproduce**

The below is the code used to reproduce this issue. Note I've imported `synthesizer.parametric.Stars` as StarsParametric to avoid confusion with `synthesizer.particle.Stars`. I'm using 'bpass-2.2.1-bin_chabrier03-0.1,100.0_cloudy-c17.03' grids, and the latest version of synthesizer (I ran `git pull origin main` an hour ago). The below code is supposed to demonstrate that applying a single component dust law works fine, but applying a two component dust law using tuples of `tau_v, alpha` fails. I suspect this is because `young_emergent` and `old_emergent` are never combined into `emergent` (if that's the expected behaviour?), and then `self.spectra['emergent']` is not defined when the code attempts to return it in `get_spectra_pacman()`. If a dust emission law is included then it doesn't crash, because it returns `self.spectra["total"]` instead. 
```
metal_dist = ZDist.DeltaConstant(log10metallicity=-2.5)
bulge_sfh = SFH.ExponentiallyDeclining(tau=100*Myr, initial_age=300*Myr)

bulge_stars = StarsParametric(
    log10ages,
    metallicities,
    sf_hist=bulge_sfh,
    metal_dist=metal_dist,
    initial_mass=10**9,
)

galaxy_bulge = galaxy(bulge_stars)

# Single component instead
dust_emission_model = Greybody(20 * K, 1.2)
tau_v = 0.5
alpha = -0.7

# This works
galaxy_bulge.stars.get_spectra_pacman(grid, tau_v=tau_v, alpha=alpha, fesc=0.1),# dust_emission_model=dust_emission_ISM)
galaxy_bulge.stars.spectra = {} # Reset spectra


young_old_thresh = 10 * Myr
tau_v = (0.5, 0.5) # ISM component, birth cloud component (V band attenuation at 5500 Angstrom)
alpha = (-0.7, -1.3) # ISM component, birth cloud component (slope of the attenuation power-law curve)

# Dust emission - two component
dust_emission_ISM = Greybody(20 * K, 1.2)
dust_emission_BC = Greybody(50 * K, 1.2)
dust_emission_model = [dust_emission_ISM, dust_emission_BC]

# This line fails because self.spectra['emergent'] is never defined and cannot be returned. 
galaxy_bulge.stars.get_spectra_pacman(grid, tau_v=tau_v, alpha=alpha, fesc=0.1, young_old_thresh=young_old_thresh),# dust_emission_model=dust_emission_ISM)
```
**Expected behavior**
The method should return the expected spectra without crashing.

**Comment by WillJRoper** [comment]
Hi @tHarvey303, thanks for flagging this and sharing the details! Can you share the error message too? Something is very broken here in the logic.

**Comment by WillJRoper** [comment]
A couple more sanity checks:
- When did you download this grid? 
- Are you 100% up to date with your version of Synthesizer?

**Comment by tHarvey303** [comment]
Hi Will, sure the error message is as follows:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/home/tharvey/work/synthesizer/scripts/multi_component_galaxy.ipynb Cell 5 line 3
     [31](vscode-notebook-cell://wsl%2Bubuntu/home/tharvey/work/synthesizer/scripts/multi_component_galaxy.ipynb#X42sdnNjb2RlLXJlbW90ZQ%3D%3D?line=30) dust_emission_model = [dust_emission_ISM, dust_emission_BC]
     [33](vscode-notebook-cell://wsl%2Bubuntu/home/tharvey/work/synthesizer/scripts/multi_component_galaxy.ipynb#X42sdnNjb2RlLXJlbW90ZQ%3D%3D?line=32) # This line fails because self.spectra['emergent'] is never defined and cannot be returned. 
---> [34](vscode-notebook-cell://wsl%2Bubuntu/home/tharvey/work/synthesizer/scripts/multi_component_galaxy.ipynb#X42sdnNjb2RlLXJlbW90ZQ%3D%3D?line=33) galaxy_bulge.stars.get_spectra_pacman(grid, tau_v=tau_v, alpha=alpha, fesc=0.1, young_old_thresh=young_old_thresh),# dust_emission_model=dust_emission_ISM)

File [~/software/synthesizer/src/synthesizer/components/stellar.py:1049](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/tharvey/work/synthesizer/scripts/~/software/synthesizer/src/synthesizer/components/stellar.py:1049), in StarsComponent.get_spectra_pacman(self, grid, tau_v, dust_curve, alpha, young_old_thresh, fesc, fesc_LyA, dust_emission_model, label, **kwargs)
   [1047](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/tharvey/work/synthesizer/scripts/~/software/synthesizer/src/synthesizer/components/stellar.py:1047)     return self.spectra["total"]
   [1048](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/tharvey/work/synthesizer/scripts/~/software/synthesizer/src/synthesizer/components/stellar.py:1048) else:
-> [1049](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/tharvey/work/synthesizer/scripts/~/software/synthesizer/src/synthesizer/components/stellar.py:1049)     return self.spectra["emergent"]

KeyError: 'emergent'
```

The grid I was using was from November, but I've just downloaded `bpass-2.2.1-bin_chabrier03-0.1,300.0_cloudy-c23.01-sps.hdf5` from 4 days ago on the dropbox and I have the same issue. I'm fairly certain it's up to date, the version of synthesizer pip lists is 0.2.0a1.dev171+g274bb2dd, and `git pull origin main` says my local repo is up to date. I installed synthesizer with the -e flag so it's running off the cloned repository rather than a .egg as well. Let me know if you need anything else!

**Comment by WillJRoper** [comment]
That tag is really out of date. We're on to `v0.3.0` and about to have `v0.4.0`. However, having had a brief look at the logic the issue still appears to exist. I'll have a better look tomorrow and open a fix.

**Comment by WillJRoper** [comment]
Scratch that, it was easy. I have no idea how this oversight went untriggered for so long! Raise in PR #551. Thanks @tHarvey303!
