### ISSUE TITLE
Unit conversion issue in Sed.get_photo_fluxes() / PhotometryCollection

### ISSUE THREAD

**Issue by tHarvey303** [flaresimulations/synthesizer#557]
I appear to be on a bit of a roll today with finding bugs - this one occurs when you try and get the observed photometry from a Sed() object using a FilterCollection

```

filter_codes = [ f"JWST/NIRCam.{f}" for f in ["F090W", "F115W", "F150W", "F200W", "F277W", "F356W","F444W"]] 
fc = FilterCollection(filter_codes)
sed = galaxy_total.stars.spectra['total']
sed.get_fnu(cosmo, z,  igm=Inoue14)

sed.get_photo_fluxes(fc)

for f in fc:
    print(sed.photo_fluxes[f.filter_code].to('Jy'))


```
Output: 

4.161127698533295e+23 Jy
1.1973149647778228e+24 Jy
2.4877961254186274e+24 Jy
4.244132463292417e+24 Jy
7.883801023680302e+24 Jy
1.0892201220122101e+25 Jy
1.2815644723661375e+25 Jy
 
These numbers are _slightly_ unreasonable - digging into it, the bb_flux variable on line 1029 of sed.py, where the filters are actually applied, looks reasonable (output below), and are in fact the same as the numbers above with the wrong conversion applied. The issue appears to come from line 1034, where the output `PhotometryCollection` object is initialized.  

4.161127698533296 nJy
11.97314964777823 nJy
24.87796125418628 nJy
42.44132463292418 nJy
78.83801023680304 nJy
108.92201220122105 nJy
128.1564472366138 nJy

I'm not quite sure how the problem actually arises. Inside the init of PhotometryCollection(), the inital definition of photometry, which is a list of unyt quantites, looks reasonable.
`
[unyt_quantity(4.1611277, 'nJy'), unyt_quantity(11.97314965, 'nJy'), unyt_quantity(24.87796125, 'nJy'), unyt_quantity(42.44132463, 'nJy'), unyt_quantity(78.83801024, 'nJy'), unyt_quantity(108.9220122, 'nJy'), unyt_quantity(128.15644724, 'nJy')]`

But by the time we get to line 80, where self.photo_fluxes is set to photometry, self.photo_fluxes becomes a 'unyt_array' which looks like this. 

```
 [  4.1611277   11.97314965  24.87796125  42.44132463  78.83801024
 108.9220122  128.15644724] erg/(Hz*cm**2*s)
```

The fix is fairly simple, but I don't understand it. At the start of the PhotometyCollection class definition on line 47, before the init, photo_fluxes is predefined as a Quantity(), like below. **Simply commenting this line out returns the expected fluxes.**

photo_fluxes = Quantity()

The output of the above code then looks reasonable. 

4.161127698533296e-09 Jy
1.197314964777823e-08 Jy
2.487796125418628e-08 Jy
4.244132463292418e-08 Jy
7.883801023680305e-08 Jy
1.0892201220122106e-07 Jy
1.281564472366138e-07 Jy

I guess when self.photo_fluxes is set in the __init__, it recognizes this and assigns it to the Quantity - and the unit is reset back to a default? I don't really understand this behaviour. I'm also wondering if this is mistakenly happening anywhere else?

**Comment by WillJRoper** [comment]
You're hired! 😂 

But this is extremely weird. The photometry units should be `erg/(Hz*cm**2*s)` according to the default unit system (you can modify this but the default is defined here https://github.com/flaresimulations/synthesizer/blob/main/src/synthesizer/units.py#L94). A lot of interim steps look suspect here!

I'll have to look into this in a bit more depth. I'd guess a unitless version is being passed somewhere unintentionally and a necessary conversion is being ignored.

**Comment by tHarvey303** [comment]
Happy to help! And yeah as far as I'm aware I haven't overridden any defaults, I'm just importing, I don't redefine a new Units() object at any stage. And my local default units dictionary is the same as the version in the GitHub code.

**Comment by WillJRoper** [comment]
Oh yea, not for a second did I mean you had caused the error. Just saying if you want to swap to `nJy` as the unit used you can.

**Comment by WillJRoper** [comment]
This actually explains an issue I encountered and then never revisited making observed images! The conversion logic was failing. See the PR for a fuller description but turned out to be an easy fix after some digging.
