### ISSUE TITLE
`read_lines` on a `Grid` is used as short hand for "run through cloudy"

### ISSUE THREAD

**Issue by WillJRoper** [flaresimulations/synthesizer#560]
In a few places, the `read_lines` flag is used to detect if a grid has been run through cloudy. This isn't particularly informative and at worst could lead to misunderstandings. It would be good to provide a more explicit flag.

**Comment by stephenmwilkins** [comment]
I think this was only introduced to stop reading line grids if they're not needed, however I don't think that's necessary as the lines shouldn't add much of a memory overhead?

Related is the fact that Grids fail if they haven't been reprocessed and read_lines is not explicitly set to false. Can fix both in the same go.

IMO It would be better if a flag e.g. `reprocessed` was automatically set if the chosen grid has been reprocessed with cloudy.

**Comment by WillJRoper** [comment]
Exactly my point. There are few other issues in `grid.py` I'll post when I go through it typing it. These can all be addressed at once.
