### ISSUE TITLE
Masking issue in blackhole modelling

### ISSUE THREAD

**Issue by stephenmwilkins** [flaresimulations/synthesizer#567]
The current use of masks means that if the disc is behind the torus the `disc_incident` emission is set to zero. This problematic since then the torus emission is zero. This can be fixed by setting the mask for the `disc_incident` creation to `None` and multiplying `self.spectra["disc_incident"]` by `mask` when calculating the total transmitted spectra. 

There was also a bug where a zero spectra was set as `np.zeros(grid.lam)` instead of `np.zeros(len(grid.lam))`

Fix incoming.

**Comment by WillJRoper** [comment]
Fixed in #570
