### ISSUE TITLE
Naming of spectra generation methods in `components/blackhole` needs to relate to the model

### ISSUE THREAD

**Issue by stephenmwilkins** [flaresimulations/synthesizer#568]
Naming of spectra generation methods in `components/blackhole` needs to relate to the model. For example, `_get_spectra_torus` only relates to the `UnifiedAGN` model. Unless we store these methods elsewhere (my preference) they need to have clear names, e.g. `_get_spectra_unifiedagn_torus`. 

Similarly, `get_spectra_incident` needs a check on which model to use beyond excluding just `Template`.

**Comment by WillJRoper** [comment]
I disagree. Any model can have a torus. If have a model that doesn't implement a torus uses this method then an error or warning can be raised. Same goes for the other methods. They aren't specific to the UnifiedAGN model, they're parts of a black hole.

**Comment by stephenmwilkins** [comment]
While it's true that other BH models may have a torus (and line region) the way in which a torus (and the line regions) are modelled in the UnifiedAGN are specific to that model. As an example, the torus model in UnifiedAGN is completely optically think, i.e. once your inclination passes the opening angle of the torus, the disc emission is totally attenuated. A more sophisticated torus model could do something different. I think it's clearer to define a set of methods for a particular model.

**Comment by WillJRoper** [comment]
Closing this issue since our discussions have moved towards having the specific generation methods private on an emission model with front facing catch all methods on a component.
