### ISSUE TITLE
standardise doc string format

### ISSUE THREAD

**Issue by christopherlovell** [flaresimulations/synthesizer#57]

**Comment by WillJRoper** [comment]
Shall we simply say Numpydoc and be done with it? We can pin template for them so everyone has quick access to a class and function template.

**Comment by christopherlovell** [comment]
- [ ] igm.py
- [ ] abundances.py
- [ ] agn.py
- [ ] cloudy.py
- [ ] dust.py
- [ ] exceptions.py
- [ ] filters.py
- [ ] galaxy,.py
- [ ] grid.py
- [ ] kernel_functions.py
- [ ] line.py
- [ ] load_data.py
- [ ] observations.py
- [ ] plt.py
- [ ] sed.py
- [ ] stats.py
- [ ] utils.py
- [ ] weights.pyx

**Comment by WillJRoper** [comment]
This is a really nice quick link for templates for all the different situations: https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html

**Comment by christopherlovell** [comment]
numpy doc example from @WillJRoper 
```

"""
Example function with types documented in the docstring.

Parameters
----------
param1 : int
    The first parameter.
param2 : str
    The second parameter.

Returns
-------
bool
    True if successful, False otherwise.

Raises
-------

"""

For classes this has Attribute and Methods sections.

```

**Comment by christopherlovell** [comment]
Switched to Google format as default, details [here](https://google.github.io/styleguide/pyguide.html#s3.8-comments-and-docstrings), upcoming PR to implement
