### ISSUE TITLE
Add ability to add spectra with different wavelength grids

### ISSUE THREAD

**Issue by stephenmwilkins** [flaresimulations/synthesizer#572]
When adding `Sed` objects together it would be good to be able to add spectra with different wavelength grids. This might mean using `spectres` or something custom.

**Comment by WillJRoper** [comment]
Having thought more about this I don't know about anyone else (@christopherlovell?) but I'd much rather do what we do now and throw an error and make the user resample (the tools exist) rather than do something quietly behind the scenes. We can reopen this issue if anyone strongly disagrees.
