### ISSUE TITLE
Instances of metals over metallicities

### ISSUE THREAD

**Issue by aswinpvijayan** [flaresimulations/synthesizer#578]
In particles/galaxy.py, there are instances in load stars and load_gas, where 'metals' is used instead of 'metallicities' (e.g. https://github.com/flaresimulations/synthesizer/blob/main/src/synthesizer/particle/galaxy.py#L173). These are the only instance where I could see metals being used (also load_data/load_flares.py, which is related). Is that a definition that is currently followed?
@christopherlovell @WillJRoper @stephenmwilkins

**Comment by christopherlovell** [comment]
I'd suggest we change all these to metallicities. Metals can be reserved for individual element abundances

**Comment by aswinpvijayan** [comment]
I have changed it in branch rm_metals, which I will open PR now
