### ISSUE TITLE
Method named wrong 

### ISSUE THREAD

**Issue by christopherlovell** [flaresimulations/synthesizer#582]
Shouldn't this be `get_spectra_intrinsic`? Since it allows you to choose an escape fraction

https://github.com/flaresimulations/synthesizer/blob/053f20d82c4495309fbac7123c6423c4e9640ccb/src/synthesizer/components/stellar.py#L322

**Comment by WillJRoper** [comment]
I think I prefer intrinsic but wasn't this part of the long spectra naming discussion? 

Happy to make that change but we should keep reprocessed wrapping intrinsic and add a deprecation warning when it is called.

**Comment by christopherlovell** [comment]
I think intrinsic actually wraps this and sets `fesc=0` by default

**Comment by WillJRoper** [comment]
Sounds good to me.

**Comment by stephenmwilkins** [comment]
@christopherlovell where's the diagram again?

**Comment by christopherlovell** [comment]
https://flaresimulations.github.io/synthesizer/spectra.html
