### ISSUE TITLE
Store both vacuum and "standard" wavelengths for lines

### ISSUE THREAD

**Issue by stephenmwilkins** [flaresimulations/synthesizer#591]
At the moment we're adopting the cloudy standard for the wavelengths of lines (air @ >200nm, vacuum @ <200nm). However we should store both vacuum and standard wavelengths. It might also be useful to be able to call a line using either ID variant, though I'm not sure how easily that could be implemented.

**Comment by WillJRoper** [comment]
I think this was solved in #552, @stephenmwilkins?
