### ISSUE TITLE
Need to decide on a doc string template

### ISSUE THREAD

**Issue by WillJRoper** [flaresimulations/synthesizer#60]
My personal preference is the Numpydoc style. 

    """
    Example function with types documented in the docstring.

    Parameters
    ----------
    param1 : int
        The first parameter.
    param2 : str
        The second parameter.

    Returns
    -------
    bool
        True if successful, False otherwise.

    Raises
    -------

    """
    
    For classes this has Attribute and Methods sections.

**Comment by christopherlovell** [comment]
duplicate of #57
