### ISSUE TITLE
Key error due to old wavelengths

### ISSUE THREAD

**Issue by sophie-newman** [flaresimulations/synthesizer#602]
The line `x_, y_ = lines.get_diagram(diagram_id)` no longer works as it results in a key error:
`KeyError: 'H 1 6564.62A'` in line.py

I am unsure why the old wavelength is being used.

To plot diagnostic diagrams, I now have to work the ratios out manually instead

**Comment by WillJRoper** [comment]
Have you updated your grid file?

**Comment by stephenmwilkins** [comment]
@sophie-newman yes, unfortunately, when it comes to lines all the old grids will now be broken as we've moved to "cloudy standard" wavelength conventions (vacuum <2000\AA, air > 2000\AA). 

You could either re-run the grid creation or create a version of the line_ratios module with just vacuum wavelengths.

**Comment by WillJRoper** [comment]
Closing, since this is not a Synthesizer issue but instead a grid file problem.
