### ISSUE TITLE
Automatic creation of integrated quantities

### ISSUE THREAD

**Issue by stephenmwilkins** [flaresimulations/synthesizer#606]
I believe we discussed this before but I think when creating particle spectra/lines we should automatically create the integrated version.

In cases where you want both this would save adding an additional calculation and really wouldn't add much overheads at all.

**Comment by WillJRoper** [comment]
I really don't like doing things that effect the front end (I.e. what's available on a object) automatically behind the scenes with no signposts for the user. The user isn't going to automatically know that will happen. 

We could change it to get_particle_and_integrated_spectra_* but I hate that. Calling a sum on an Sed or the integrated method is more readable. Additionally, sure the integrated spectra is a small memory footprint but small memory footprints add up over time and could be the difference between a crash and not when near the memory limits.

**Comment by stephenmwilkins** [comment]
How about the compromise of a flag on the method that calculates the integrated value if true? 

If you're creating particle spectra etc. the memory footprint must be tiny considering that galaxies on average have at least 1000 particles right?

**Comment by WillJRoper** [comment]
But why? There's a method right there, it's one line and shoes in intention in the pipeline far better than inflating the number of arguments.

@christopherlovell you can have deciding vote but my vote is close this issue and have it explicit based on method call.

**Comment by stephenmwilkins** [comment]
But doesn't that mean doing the entire calculation twice?

**Comment by WillJRoper** [comment]
Not really, the integrated calculation is different and insignificant in cost comparatively but really you should just use the 'sum' method on the Sed.

**Comment by WillJRoper** [comment]
Closing since I think this has been handled in the introduction of summing methods on lines (which were missing) and I am far from keen on doing things automatically without the user intending them to happen.
