### ISSUE TITLE
Integrated line creation methods don't account for dust properly

### ISSUE THREAD

**Issue by stephenmwilkins** [flaresimulations/synthesizer#607]
From what I can tell, `component.stars.get_line_attenuated`, first generates the **integrated** line luminosity and then applies dust. However, this doesn't work since the dust needs to be applied to each individual particle. At the moment this simply duplicates the integrated line luminosity for every particle for the different attenuations.

The easiest fix is that this just calls the particle/parametric method and sums where necessary; however, this puts all the star particle data in memory I guess.

**Comment by WillJRoper** [comment]
This isn't incorrect but I don't think that's the issue. The integrated attenuation should only take a single tau representative of the entire integrated line/spectrum. 

This has been discussed/is in the docs but the method used for multiple particles with spectra should be the 'apply_attenuation' method on a Sed. Maybe we need something similar on a Line which can handle arrays of tau. 

The component can never call a particle method.

**Comment by stephenmwilkins** [comment]
Then I have deeply misunderstood the point of integrated attenuation and I think that needs a further discussion because I really don't think this is desirable. 

I thought 'integrated' in this context would simply sum the particle spectra/line luminosities without holding on to the data.

**Comment by WillJRoper** [comment]
Have you looked at any of the simulation pipelines? They all work on particles when there are multiple taus and then integrate. You don't always have a tau for each particle (e.g. a screen around the galaxy). If you do you should work with particle spectra/lines.

I think all your issues would be solved by making an `apply_attenuation` method on a Line which can be used in the other methods.
