### ISSUE TITLE
In general there are far too few comments

### ISSUE THREAD

**Issue by WillJRoper** [flaresimulations/synthesizer#61]
The are swathes of code where the only comment is a doc string with minimal detail. This has to be addressed throughout before it's too late. 

Comments should obey PEP-8:

Comments on their own line start with a space and a capital 
```# Comment```
Inline comments are two spaces from the end of the line and start with a lower case letter
```code  # comment```

Dashes should only be used to separate code blocks to aide readability.

**Comment by christopherlovell** [comment]
Be more specific. Particular methods welcome. For example, the igm `Inoue14` class is particularly poorly documented (doc strings a first requirement) @stephenmwilkins 

https://github.com/flaresimulations/synthesizer/blob/main/synthesizer/igm.py#L13

**Comment by WillJRoper** [comment]
It's hard to be specific when it's prevalent everywhere. The entirety of filters.py for instance, kernel_functions.py doesn't have a single comment beyond a long doc string. Compare any script to images.py. 

Unless a line explicitly says what it is doing it needs a comment, if a choice was made as to why a computation is done the way it is that should be explained in a comment.

**Comment by WillJRoper** [comment]
It's fine to be a bit lax when developing and things are in flux but before merging. At a minimum 1/3 of the code should be comments IMO.

**Comment by christopherlovell** [comment]
Sure, we can try and carry this attitude forward for future PRs
