### ISSUE TITLE
Setting DTM=0.3 for None cases

### ISSUE THREAD

**Issue by aswinpvijayan** [flaresimulations/synthesizer#638]
This https://github.com/flaresimulations/synthesizer/blob/main/src/synthesizer/particle/gas.py#L139 automatically sets DTM to 0.3 when the dust mass or DTM is not given. Logically there could be instances of where there are no gas particle in a galaxy (or when masked), that setting it automatically does not make sense. Would be best to check if for example the metallicity is None and keep the values as None.

**Comment by christopherlovell** [comment]
Agreed, feel free to raise a PR
