### ISSUE TITLE
No explanation of what this method does or why it exists (_power_law_sample).

### ISSUE THREAD

**Issue by WillJRoper** [flaresimulations/synthesizer#65]
https://github.com/flaresimulations/synthesizer/blob/1886b38f74ed14eda2da4700465b4c8993c7df50/synthesizer/particle/stars.py#L81

Also non-PEP-8 math formating.

**Comment by christopherlovell** [comment]
updated in #66

**Comment by christopherlovell** [comment]
fixed in `e0f7bf55cbaa93f9a95bc0d96bcf84a041fcf329`
