### ISSUE TITLE
Particles inheritence currently serves no purpose

### ISSUE THREAD

**Issue by WillJRoper** [flaresimulations/synthesizer#67]
https://github.com/flaresimulations/synthesizer/blob/1886b38f74ed14eda2da4700465b4c8993c7df50/synthesizer/particle/stars.py#L8

I just realised the Particles parent `__init__` is never called and only contains the coordinates which are actually optional arguments for stars. 

I do think we should store common things in the parent class but we will have to account for all the optional possibilities. For now I'll leave it but this needs addressing in the long run.

**Comment by stephenmwilkins** [comment]
The only thing I can think is if there are methods common to `stars` and `gas`, for example to make a mass distribution direct from a stars object? Obviously that's functionality in pysphviewer but could serve a purpose here?

**Comment by stephenmwilkins** [comment]
Or a method give the half-mass size etc.?

**Comment by WillJRoper** [comment]
Indeed, and certainly some attributes cross over too.
