### ISSUE TITLE
Allow users to set attenuation instead of optical depth

### ISSUE THREAD

**Issue by stephenmwilkins** [flaresimulations/synthesizer#670]
Allow users to set V-band attenuation (in mags) instead of optical depth (`tau_v`).

**Comment by stephenmwilkins** [comment]
I guess people should be able to do the conversion themselves, but it's much more common (though wrong) to use attenuation not optical depth.

**Comment by WillJRoper** [comment]
Exactly why we shouldn't pander to it and over complicates our code ;)

**Comment by stephenmwilkins** [comment]
But usability...

**Comment by christopherlovell** [comment]
The purpose of the package isn't to change the behaviour of an entire field. If it aids usability for the majority we should include it. It will be a small helper function with little maintenance overhead.

**Comment by WillJRoper** [comment]
Ok, well there's a different request here then. I'm not about to modify `EmissionModels` to take different optical depths/attenuation instead. They take `tau_v` and that's how they are designed.

Adding a conversion to `synthesizer.conversions` is a different question and that I much more happy to consider (but not volunteering, someone else is welcome to implement).

**Comment by christopherlovell** [comment]
I see, that is more involved, and agree that we shouldn't modify the `EmissionModel` arguments. I think a helper function outside would be best @stephenmwilkins , with a small note in the documentation
