### ISSUE TITLE
Allow users to specify the optical depth at other wavelengths

### ISSUE THREAD

**Issue by stephenmwilkins** [flaresimulations/synthesizer#671]
Allow users to specify the optical depth at other wavelengths (e.g. in the UV).

**Comment by WillJRoper** [comment]
Again, as with other issue. This is just ballooning complexity for minimal improvements.

**Comment by WillJRoper** [comment]
In fact, the knock-on effect of this is pretty big because of how the underlying attenuation laws are coded up. I really don't think this is worth it.

**Comment by WillJRoper** [comment]
As mentioned in #670. If this is implemented as a conversion function in `synthesizer.conversions` I'm happy to see it implemented. I have no appetite to further complicate the underlying `EmissionModels` by enabling different optical depth arguments though, they take `tau_v`.
