### ISSUE TITLE
In ParticleGalaxy: Only possible to get integrated spectra from this line?

### ISSUE THREAD

**Issue by WillJRoper** [flaresimulations/synthesizer#74]
https://github.com/flaresimulations/synthesizer/blob/e0f7bf55cbaa93f9a95bc0d96bcf84a041fcf329/synthesizer/galaxy/particle.py#L138

Should this not be using  self.stellar_lum_array (and same below). Otherwise you can only get an SED object for the integrated SED.

**Comment by stephenmwilkins** [comment]
Yes, but doesn't the line immediately below give you array version?

**Comment by WillJRoper** [comment]
Ah yes 🤦, forget I said anything!
