### ISSUE TITLE
Add a method to create mass, SFR, dust, metallicity, age, sSFR maps to ParticleGalaxy

### ISSUE THREAD

**Issue by stephenmwilkins** [flaresimulations/synthesizer#77]
Add a method to create mass, SFR, dust, average metallicity, average age, sSFR maps to ParticleGalaxy

**Comment by WillJRoper** [comment]
To reduce the bloat I’d be tempted to modify the mass method to simply take an arbitrary property argument and have the user pass in the property to that argument.

**Comment by stephenmwilkins** [comment]
I think it's a little more complicated than that I'm afraid. For example:
- For SFR you really just want the mass map for young (t<t_SF) star particles but with different units.
- For the average quantities you want the average in the bin not the sum.
Maybe this can be achieved with providing the quantity and an optional function which defaults to `np.sum()`?

**Comment by WillJRoper** [comment]
Good point, those specific examples will require different functionality. The optional function won't work with the implementation though, an average flag would work though. In that case each pixel's count could be accumulated and then divide the sum by those counts.

**Comment by stephenmwilkins** [comment]
why couldn't the optional function work? By default it has`np.sum` but you can e.g. give it `np.median` a bit like `scipy.binned_statistic`.
