### ISSUE TITLE
Incorrect units when resampling a filter

### ISSUE THREAD

**Issue by alex-rawlings** [flaresimulations/synthesizer#802]
**Describe the bug**
When calling the `resample_filter()` method for a FilterCollection object with parameter `lam_size`, we get Angstroms squared instead of Angstroms.

**To Reproduce**
```
lams = np.linspace(2000, 55000, 1000) * angstrom
tophats = {
    "top_hat1": {"lam_eff": 25000 * angstrom, "lam_fwhm": 8000 * angstrom},
    "top_hat12": {"lam_min": 15000 * angstrom, "lam_max": 30000 * angstrom},
}
top_hat_filters = FilterCollection(tophat_dict=tophats, new_lam=lams)
top_hat_filters.resample_filters(lam_size=100)
```

**Expected behavior**
Correctly resampled filters on single wavelength array, with units of Angstrom.

**Git hash**
2fac8fe717723cb6e51a5a516f542630d22580e5

**Thoughts**
I believe the error comes in Line 776 of `filters.py`: as the given parameters to the `np.linspace()` call are already `unyt` objects, we don't need to multiply by the units again.

**Comment by christopherlovell** [comment]
This smells like a similar issue we had a couple days ago. Definitely looks like that line is the culprit. If you can test and raise a PR that would be great
