### ISSUE TITLE
Add ability to add images together when FOVs differ

### ISSUE THREAD

**Issue by WillJRoper** [flaresimulations/synthesizer#95]
To enable adding an image to another larger image the addition operator needs to be able to find the position of one `image1` in `image2` and resample `image1` onto the pixel grid at the position in `image2`. Shouldn't be too hard, but may be harder to catch errors of addition. 

Maybe rather than include this functionality in `+` it would be better to make this a method in Image `def embed_img(self, other_img)`.

**Comment by aswinpvijayan** [comment]
How would this be implemented? Would be have some sort of wcs to align images?

**Comment by stephenmwilkins** [comment]
I really don't think we need this functionality, and in fact it could be "dangerous". Just insist the user generate images on the same grid.
