### ISSUE TITLE
Additional parametrisations of the metallicity history

### ISSUE THREAD

**Issue by christopherlovell** [flaresimulations/synthesizer#96]
Only a delta function has been implemented so far

https://github.com/flaresimulations/synthesizer/blob/main/synthesizer/parametric/sfzh.py#L181

**Comment by stephenmwilkins** [comment]
Yes, this has been on my to do list for a while but I haven't decided on any other histories. I suppose:

- linear (in log10age)
- linear with gaussian width

Any others?
