### ISSUE TITLE
Why does the package reference a url plotting style?

### ISSUE THREAD

**Issue by WillJRoper** [flaresimulations/synthesizer#97]
```plt.style.use('http://stephenwilkins.co.uk/matplotlibrc.txt')``` 

Why does this exist? It just caused an error for me which thankfully allowed me to discover it.

**Comment by stephenmwilkins** [comment]
Carried over from earlier code, like the entire plt module. I guess we don't want to enforce a plotting style on users.

Incidentally something like this would probably be useful for FLARES-2 to maintain a consistent plotting style. I don't care much about the specifics just as long as it's consistent.

**Comment by stephenmwilkins** [comment]
I'm surprised it broke anything though - I've used this for years with no issue.
